[package]
name = "my_bittorrent"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
serde = { version = "1.0.217", features = ["derive"] }
serde_bencode = "0.2.4"
serde_bytes = "0.11.15"
serde_json = "1.0.135"
serde_urlencoded = "0.7.1"
